# Use MySQL image
FROM mysql:5.7

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=yourdatabase
ENV MYSQL_USER=youruser
ENV MYSQL_PASSWORD=yourpassword

# Expose the MySQL port
EXPOSE 3306